"""add_user_id_to_medical_receipts_and_rls

Revision ID: fb4488ff3ebf
Revises: 424a95acb83b
Create Date: 2026-04-05 04:08:18.754095

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb4488ff3ebf'
down_revision: Union[str, Sequence[str], None] = '424a95acb83b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email', name='uq_users_email')
    )
    op.add_column('medical_receipts', sa.Column('user_id', sa.String(length=36), nullable=False))
    op.create_index(op.f('ix_medical_receipts_user_id'), 'medical_receipts', ['user_id'], unique=False)
    op.create_foreign_key(None, 'medical_receipts', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
    op.execute("ALTER TABLE medical_receipts ENABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE medical_receipts FORCE ROW LEVEL SECURITY")
    op.execute("""
        CREATE POLICY user_isolation ON medical_receipts
            USING (user_id = current_setting('app.user_id', true))
            WITH CHECK (user_id = current_setting('app.user_id', true))
    """)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP POLICY IF EXISTS user_isolation ON medical_receipts")
    op.execute("ALTER TABLE medical_receipts DISABLE ROW LEVEL SECURITY")
    op.drop_constraint(None, 'medical_receipts', type_='foreignkey')
    op.drop_index(op.f('ix_medical_receipts_user_id'), table_name='medical_receipts')
    op.drop_column('medical_receipts', 'user_id')
    op.drop_table('users')
    # ### end Alembic commands ###
